// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Context;

#nullable disable

namespace Test.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240615091223_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.Model.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Application1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Application2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Application3"
                        });
                });

            modelBuilder.Entity("Test.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Customer1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Customer3"
                        });
                });

            modelBuilder.Entity("Test.Model.CustomerApplication", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "ApplicationId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("CustomerApplications");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ApplicationId = 1
                        },
                        new
                        {
                            CustomerId = 1,
                            ApplicationId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            ApplicationId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            ApplicationId = 3
                        },
                        new
                        {
                            CustomerId = 3,
                            ApplicationId = 1
                        },
                        new
                        {
                            CustomerId = 3,
                            ApplicationId = 3
                        });
                });

            modelBuilder.Entity("Test.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationId = 1,
                            Description = "Rule1"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationId = 1,
                            Description = "Rule2"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationId = 2,
                            Description = "Rule3"
                        },
                        new
                        {
                            Id = 4,
                            ApplicationId = 2,
                            Description = "Rule4"
                        },
                        new
                        {
                            Id = 5,
                            ApplicationId = 3,
                            Description = "Rule5"
                        });
                });

            modelBuilder.Entity("Test.Model.CustomerApplication", b =>
                {
                    b.HasOne("Test.Model.Application", "Application")
                        .WithMany("CustomerApplications")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test.Model.Customer", "Customer")
                        .WithMany("CustomerApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Test.Model.Role", b =>
                {
                    b.HasOne("Test.Model.Application", "Application")
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Test.Model.Application", b =>
                {
                    b.Navigation("CustomerApplications");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Test.Model.Customer", b =>
                {
                    b.Navigation("CustomerApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
